#!/usr/bin/env python3
"""Generates src/il_names.inc: a name for each enumerator of the IL kind enums the exporter writes.

The enumerators' values depend on the front end's configuration, so the exporter writes names, and
the switches are generated from EDG's il_def.h with its preprocessor conditionals kept: they compile
under any configuration. Aliases (`tk_enum = tk_integer`) are left out, as a switch cannot list a
value twice.

    tools/gen_il_names.py third_party/edgcpp/src/il_def.h > src/il_names.inc
"""

import re
import sys

ENUMS = {
    # enum name: (prefix stripped from each enumerator, function name)
    "an_expr_operator_kind": ("eok_", "operatorName"),
    "an_expr_node_kind": ("enk_", "nodeKindName"),
    "a_statement_kind": ("stmk_", "statementKindName"),
    "a_type_kind": ("tk_", "typeKindName"),
    "a_constant_repr_kind": ("ck_", "constantKindName"),
    "a_dynamic_init_kind": ("dik_", "dynamicInitKindName"),
    "a_storage_class": ("sc_", "storageClassName"),
    "a_name_linkage_kind": ("nlk_", "linkageName"),
    "a_special_function_kind": ("sfk_", "specialFunctionName"),
    "an_attribute_kind": ("ak_", "attributeKindName"),
    "an_opname_kind": ("onk_", "opnameName"),
    "a_typeref_kind": ("trk_", "typerefKindName"),
    "an_address_base_kind": ("abk_", "addressBaseName"),
}

ENUM_START = re.compile(r"^\s*(?:typedef\s+)?enum\s+(\w+)\b[^;{]*\{")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def enum_bodies(source):
    lines = source.split("\n")
    i = 0
    while i < len(lines):
        m = ENUM_START.match(lines[i])
        if m and m.group(1) in ENUMS:
            name = m.group(1)
            body = []
            depth = lines[i].count("{") - lines[i].count("}")
            i += 1
            while i < len(lines) and depth > 0:
                depth += lines[i].count("{") - lines[i].count("}")
                if depth > 0:
                    body.append(lines[i])
                i += 1
            yield name, "\n".join(body)
        else:
            i += 1


def entries(body):
    """Preprocessor lines and enumerator names, in order; aliases dropped."""
    out = []
    text = strip_comments(body)
    for raw in text.split("\n"):
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            out.append(("pp", line))
            continue
        for part in line.split(","):
            part = part.strip()
            if not part:
                continue
            m = re.match(r"^([A-Za-z_]\w*)\s*(?:=\s*(.+))?$", part)
            if not m:
                continue
            value = (m.group(2) or "").strip()
            # an alias names another enumerator; a numeric value is not an alias
            if value and re.match(r"^[A-Za-z_]\w*$", value):
                continue
            out.append(("e", m.group(1)))
    return out


def main():
    source = open(sys.argv[1], encoding="latin-1").read()
    print("// Generated by tools/gen_il_names.py from EDG's il_def.h; do not edit.")
    found = set()
    for name, body in enum_bodies(source):
        if name in found:
            continue
        found.add(name)
        prefix, function = ENUMS[name]
        print(f"\nstatic const char *{function}({name} kind) {{")
        print("  switch (kind) {")
        for kind, value in entries(body):
            if kind == "pp":
                print(value)
            elif value.endswith("_last") or value.startswith("last_") or value.endswith("_LAST"):
                continue
            else:
                short = value[len(prefix):] if value.startswith(prefix) else value
                print(f'    case {value}: return "{short}";')
        print("    default: return \"unknown\";")
        print("  }")
        print("}")
    missing = set(ENUMS) - found
    if missing:
        sys.exit(f"enums not found in {sys.argv[1]}: {', '.join(sorted(missing))}")


if __name__ == "__main__":
    main()
